### Hello World
POST http://localhost:8082/run
Content-Type: application/json

{
  "script": "console.log('Hello, World!');",
  "functionName": "",
  "input": ""
}

### Addition
POST http://localhost:8082/run
Content-Type: application/json

{
  "script": "export function add({a, b}) { return a + b; }",
  "functionName": "add",
  "input": {"a": 5, "b": 7},
  "verbose": false
}
