### Hello World
POST http://localhost:8082/kratos.runtime.nodejs/22-latest/script/run
Content-Type: application/json

{
  "data": {
    "script": "console.log('Hello, World!');",
    "function": "",
    "input": ""
  }
}

### Addition
POST http://localhost:8082/kratos.runtime.nodejs/22-latest/script/run
Content-Type: application/json

{
  "data": {
    "script": "export function add({a, b}) { return a + b; }",
    "function": "add",
    "input": {
      "a": 5,
      "b": 7
    },
    "verbose": false
  }
}
